default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: myapp
  password: password1
  host: <%= ENV['IP'] %>
  
  #adapter: postgresql
  #encoding: unicode
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #username: myapp
  #password: password1
  #host: localhost
  ##sudo service postgresql start

development:
  <<: *default
  database: find-restaurant_development

test:
  <<: *default
  database: find-restaurant_test

production:
  <<: *default
  database: find-restaurant_production
  username: find-restaurant
  password: <%= ENV['FIND-RESTAURANT_DATABASE_PASSWORD'] %>
